stages:
  - build-docker
  - deploy

variables:
  APPLICATION_ARTIFACTS_PATH: /

manual_build_docker:
  stage: build-docker
  tags: [docker]
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - cp -r $APPLICATION_ARTIFACTS_PATH ./docker/build
    - docker build ./docker -t webapi
    - docker tag webapi $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  only:
    - /^(feature.*)$/
  when: manual
  
auto_build_docker:
  stage: build-docker
  tags: [docker]
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - cp -r $APPLICATION_ARTIFACTS_PATH ./docker/build
    - docker build ./docker -t webapi
    - docker tag webapi $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  only:
    - /^(master|develop|v*)$/
